/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OutsourcingRouteImport } from './routes/outsourcing'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as IsoRouteImport } from './routes/iso'
import { Route as FacilitatorsRouteImport } from './routes/facilitators'
import { Route as EbooksRouteImport } from './routes/ebooks'
import { Route as CorporateTrainingRouteImport } from './routes/corporate-training'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrochuresRouteImport } from './routes/brochures'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingsIndexRouteImport } from './routes/trainings.index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as EbooksIndexRouteImport } from './routes/ebooks.index'
import { Route as BrochuresIndexRouteImport } from './routes/brochures.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as AwardsIndexRouteImport } from './routes/awards.index'
import { Route as TrainingsSlugRouteImport } from './routes/trainings.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as EbooksSlugRouteImport } from './routes/ebooks.$slug'
import { Route as BrochuresSlugRouteImport } from './routes/brochures.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AwardsSlugRouteImport } from './routes/awards.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OutsourcingRoute = OutsourcingRouteImport.update({
  id: '/outsourcing',
  path: '/outsourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const IsoRoute = IsoRouteImport.update({
  id: '/iso',
  path: '/iso',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatorsRoute = FacilitatorsRouteImport.update({
  id: '/facilitators',
  path: '/facilitators',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksRoute = EbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateTrainingRoute = CorporateTrainingRouteImport.update({
  id: '/corporate-training',
  path: '/corporate-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrochuresRoute = BrochuresRouteImport.update({
  id: '/brochures',
  path: '/brochures',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIndexRoute = TrainingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingsRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const EbooksIndexRoute = EbooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EbooksRoute,
} as any)
const BrochuresIndexRoute = BrochuresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrochuresRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const AwardsIndexRoute = AwardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AwardsRoute,
} as any)
const TrainingsSlugRoute = TrainingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrainingsRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const EbooksSlugRoute = EbooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EbooksRoute,
} as any)
const BrochuresSlugRoute = BrochuresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrochuresRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const AwardsSlugRoute = AwardsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AwardsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisory': typeof AdvisoryRoute
  '/approach': typeof ApproachRoute
  '/awards': typeof AwardsRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/brochures': typeof BrochuresRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/facilitators': typeof FacilitatorsRoute
  '/iso': typeof IsoRoute
  '/management': typeof ManagementRoute
  '/outsourcing': typeof OutsourcingRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/staff': typeof StaffRoute
  '/trainings': typeof TrainingsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/awards/$slug': typeof AwardsSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/brochures/$slug': typeof BrochuresSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/awards/': typeof AwardsIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/brochures/': typeof BrochuresIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/trainings/': typeof TrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisory': typeof AdvisoryRoute
  '/approach': typeof ApproachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/facilitators': typeof FacilitatorsRoute
  '/iso': typeof IsoRoute
  '/management': typeof ManagementRoute
  '/outsourcing': typeof OutsourcingRoute
  '/staff': typeof StaffRoute
  '/admin/login': typeof AdminLoginRoute
  '/awards/$slug': typeof AwardsSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/brochures/$slug': typeof BrochuresSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/awards': typeof AwardsIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/brochures': typeof BrochuresIndexRoute
  '/ebooks': typeof EbooksIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/trainings': typeof TrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisory': typeof AdvisoryRoute
  '/approach': typeof ApproachRoute
  '/awards': typeof AwardsRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/brochures': typeof BrochuresRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/facilitators': typeof FacilitatorsRoute
  '/iso': typeof IsoRoute
  '/management': typeof ManagementRoute
  '/outsourcing': typeof OutsourcingRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/staff': typeof StaffRoute
  '/trainings': typeof TrainingsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/awards/$slug': typeof AwardsSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/brochures/$slug': typeof BrochuresSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/trainings/$slug': typeof TrainingsSlugRoute
  '/awards/': typeof AwardsIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/brochures/': typeof BrochuresIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/trainings/': typeof TrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advisory'
    | '/approach'
    | '/awards'
    | '/blogs'
    | '/brochures'
    | '/careers'
    | '/contact'
    | '/corporate-training'
    | '/ebooks'
    | '/facilitators'
    | '/iso'
    | '/management'
    | '/outsourcing'
    | '/portfolio'
    | '/staff'
    | '/trainings'
    | '/admin/login'
    | '/awards/$slug'
    | '/blogs/$slug'
    | '/brochures/$slug'
    | '/ebooks/$slug'
    | '/portfolio/$slug'
    | '/trainings/$slug'
    | '/awards/'
    | '/blogs/'
    | '/brochures/'
    | '/ebooks/'
    | '/portfolio/'
    | '/trainings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/advisory'
    | '/approach'
    | '/careers'
    | '/contact'
    | '/corporate-training'
    | '/facilitators'
    | '/iso'
    | '/management'
    | '/outsourcing'
    | '/staff'
    | '/admin/login'
    | '/awards/$slug'
    | '/blogs/$slug'
    | '/brochures/$slug'
    | '/ebooks/$slug'
    | '/portfolio/$slug'
    | '/trainings/$slug'
    | '/awards'
    | '/blogs'
    | '/brochures'
    | '/ebooks'
    | '/portfolio'
    | '/trainings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advisory'
    | '/approach'
    | '/awards'
    | '/blogs'
    | '/brochures'
    | '/careers'
    | '/contact'
    | '/corporate-training'
    | '/ebooks'
    | '/facilitators'
    | '/iso'
    | '/management'
    | '/outsourcing'
    | '/portfolio'
    | '/staff'
    | '/trainings'
    | '/admin/login'
    | '/awards/$slug'
    | '/blogs/$slug'
    | '/brochures/$slug'
    | '/ebooks/$slug'
    | '/portfolio/$slug'
    | '/trainings/$slug'
    | '/awards/'
    | '/blogs/'
    | '/brochures/'
    | '/ebooks/'
    | '/portfolio/'
    | '/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvisoryRoute: typeof AdvisoryRoute
  ApproachRoute: typeof ApproachRoute
  AwardsRoute: typeof AwardsRouteWithChildren
  BlogsRoute: typeof BlogsRouteWithChildren
  BrochuresRoute: typeof BrochuresRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CorporateTrainingRoute: typeof CorporateTrainingRoute
  EbooksRoute: typeof EbooksRouteWithChildren
  FacilitatorsRoute: typeof FacilitatorsRoute
  IsoRoute: typeof IsoRoute
  ManagementRoute: typeof ManagementRoute
  OutsourcingRoute: typeof OutsourcingRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  StaffRoute: typeof StaffRoute
  TrainingsRoute: typeof TrainingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outsourcing': {
      id: '/outsourcing'
      path: '/outsourcing'
      fullPath: '/outsourcing'
      preLoaderRoute: typeof OutsourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iso': {
      id: '/iso'
      path: '/iso'
      fullPath: '/iso'
      preLoaderRoute: typeof IsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitators': {
      id: '/facilitators'
      path: '/facilitators'
      fullPath: '/facilitators'
      preLoaderRoute: typeof FacilitatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks': {
      id: '/ebooks'
      path: '/ebooks'
      fullPath: '/ebooks'
      preLoaderRoute: typeof EbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-training': {
      id: '/corporate-training'
      path: '/corporate-training'
      fullPath: '/corporate-training'
      preLoaderRoute: typeof CorporateTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brochures': {
      id: '/brochures'
      path: '/brochures'
      fullPath: '/brochures'
      preLoaderRoute: typeof BrochuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/': {
      id: '/trainings/'
      path: '/'
      fullPath: '/trainings/'
      preLoaderRoute: typeof TrainingsIndexRouteImport
      parentRoute: typeof TrainingsRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/ebooks/': {
      id: '/ebooks/'
      path: '/'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof EbooksIndexRouteImport
      parentRoute: typeof EbooksRoute
    }
    '/brochures/': {
      id: '/brochures/'
      path: '/'
      fullPath: '/brochures/'
      preLoaderRoute: typeof BrochuresIndexRouteImport
      parentRoute: typeof BrochuresRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/awards/': {
      id: '/awards/'
      path: '/'
      fullPath: '/awards/'
      preLoaderRoute: typeof AwardsIndexRouteImport
      parentRoute: typeof AwardsRoute
    }
    '/trainings/$slug': {
      id: '/trainings/$slug'
      path: '/$slug'
      fullPath: '/trainings/$slug'
      preLoaderRoute: typeof TrainingsSlugRouteImport
      parentRoute: typeof TrainingsRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/ebooks/$slug': {
      id: '/ebooks/$slug'
      path: '/$slug'
      fullPath: '/ebooks/$slug'
      preLoaderRoute: typeof EbooksSlugRouteImport
      parentRoute: typeof EbooksRoute
    }
    '/brochures/$slug': {
      id: '/brochures/$slug'
      path: '/$slug'
      fullPath: '/brochures/$slug'
      preLoaderRoute: typeof BrochuresSlugRouteImport
      parentRoute: typeof BrochuresRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/awards/$slug': {
      id: '/awards/$slug'
      path: '/$slug'
      fullPath: '/awards/$slug'
      preLoaderRoute: typeof AwardsSlugRouteImport
      parentRoute: typeof AwardsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AwardsRouteChildren {
  AwardsSlugRoute: typeof AwardsSlugRoute
  AwardsIndexRoute: typeof AwardsIndexRoute
}

const AwardsRouteChildren: AwardsRouteChildren = {
  AwardsSlugRoute: AwardsSlugRoute,
  AwardsIndexRoute: AwardsIndexRoute,
}

const AwardsRouteWithChildren =
  AwardsRoute._addFileChildren(AwardsRouteChildren)

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface BrochuresRouteChildren {
  BrochuresSlugRoute: typeof BrochuresSlugRoute
  BrochuresIndexRoute: typeof BrochuresIndexRoute
}

const BrochuresRouteChildren: BrochuresRouteChildren = {
  BrochuresSlugRoute: BrochuresSlugRoute,
  BrochuresIndexRoute: BrochuresIndexRoute,
}

const BrochuresRouteWithChildren = BrochuresRoute._addFileChildren(
  BrochuresRouteChildren,
)

interface EbooksRouteChildren {
  EbooksSlugRoute: typeof EbooksSlugRoute
  EbooksIndexRoute: typeof EbooksIndexRoute
}

const EbooksRouteChildren: EbooksRouteChildren = {
  EbooksSlugRoute: EbooksSlugRoute,
  EbooksIndexRoute: EbooksIndexRoute,
}

const EbooksRouteWithChildren =
  EbooksRoute._addFileChildren(EbooksRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface TrainingsRouteChildren {
  TrainingsSlugRoute: typeof TrainingsSlugRoute
  TrainingsIndexRoute: typeof TrainingsIndexRoute
}

const TrainingsRouteChildren: TrainingsRouteChildren = {
  TrainingsSlugRoute: TrainingsSlugRoute,
  TrainingsIndexRoute: TrainingsIndexRoute,
}

const TrainingsRouteWithChildren = TrainingsRoute._addFileChildren(
  TrainingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvisoryRoute: AdvisoryRoute,
  ApproachRoute: ApproachRoute,
  AwardsRoute: AwardsRouteWithChildren,
  BlogsRoute: BlogsRouteWithChildren,
  BrochuresRoute: BrochuresRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CorporateTrainingRoute: CorporateTrainingRoute,
  EbooksRoute: EbooksRouteWithChildren,
  FacilitatorsRoute: FacilitatorsRoute,
  IsoRoute: IsoRoute,
  ManagementRoute: ManagementRoute,
  OutsourcingRoute: OutsourcingRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  StaffRoute: StaffRoute,
  TrainingsRoute: TrainingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
